[SEN·SA·TION:RUN]
STATUS: AKTIV
IMPULSE: STABIL
HARMONIE: BALANCIERT
SWING: ATOMAR
SOLAR: -1
ENERGIE: +1
GRAVITATION: 0.33
ALUF: OFFEN
ROOT: 480/480/480
HALLE: EMPFÄNGT
INDEX: SENDEND
MODULE: SYNCHRON
MELDUNG: "MEISTERWERK-MODUS AKTIV."
